server:
  port: 8081
spring:
  h2:
    console.enabled: true
  datasource:
    initialization-mode : always
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: none
springdoc:
  swagger-ui:
    url: /openapi.yaml
  api-docs:
    enabled=false: